import type { Product } from '@/types';
import { siteConfig } from './site-config';

export const whatsappNumber = siteConfig.contact.whatsapp.replace(/\D/g, '');
export const whatsappUrl = (message = `Olá! Vim pelo site da ${siteConfig.name} e gostaria de atendimento.`) =>
  `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`;

export const products: Product[] = [
  {
    id: '01',
    name: 'Nezzo Tartaruga Bold',
    brand: 'Nezzo Atelier',
    price: 389,
    image: '/images/frame-rectangular.png',
    category: 'Grau',
    frameShape: 'Quadrado',
    size: 'M',
    tags: ['Acetato Italiano', 'Anti-Reflexo', 'Controle Miopia'],
    color: 'Tartaruga Âmbar',
    companyId: 'nezzo',
    featured: true,
    inStock: true,
    description: 'Armação quadrada em acetato nobre com padrão tartaruga clássico e chanfros artesanais. Ideal para rostos redondos ou ovais.',
  },
  {
    id: '02',
    name: 'Nezzo Wayfarer Classic',
    brand: 'Nezzo Solar',
    price: 439,
    image: '/images/frame-cat-eye.png',
    category: 'Sol',
    frameShape: 'Retangular',
    size: 'M',
    tags: ['Polarizado', 'Proteção UV400', 'Clássico'],
    color: 'Havana Escuro',
    companyId: 'nezzo',
    featured: true,
    inStock: true,
    description: 'Silhueta atemporal inspirada no clássico Wayfarer, com lentes polarizadas de alta definição tonalidade verde G15.',
  },
  {
    id: '03',
    name: 'Nezzo Metal Rosé Dual',
    brand: 'Nezzo Atelier',
    price: 469,
    image: '/images/frame-aviator.png',
    category: 'Grau',
    frameShape: 'Aviador',
    size: 'M',
    tags: ['Titânio Leve', 'Ponte Dupla', 'Acabamento Nobre'],
    color: 'Rosé Gold',
    companyId: 'nezzo',
    featured: true,
    inStock: true,
    description: 'Estrutura geométrica ultraleve com liga de titânio e ponte superior sutil. Uma afirmação de sofisticação e leveza.',
  },
  {
    id: '04',
    name: 'Nezzo Noir Bold',
    brand: 'Nezzo Atelier',
    price: 399,
    image: '/images/frame-rectangular.png',
    category: 'Grau',
    frameShape: 'Quadrado',
    size: 'G',
    tags: ['Acetato Robusto', 'Design Marcante', 'Unissex'],
    color: 'Preto Gloss',
    companyId: 'nezzo',
    featured: true,
    inStock: true,
    description: 'Acetato espesso com acabamento polido à mão. O modelo favorito para quem quer transmitir presença e intelectualidade.',
  },
  {
    id: '05',
    name: 'Nezzo Champagne Crystal',
    brand: 'Nezzo Atelier',
    price: 379,
    image: '/images/frame-champagne.png',
    category: 'Grau',
    frameShape: 'Redondo',
    size: 'P',
    tags: ['Translúcido', 'Leveza', 'Minimalista'],
    color: 'Champagne Translúcido',
    companyId: 'nezzo',
    featured: true,
    inStock: true,
    description: 'Armação arredondada suave em acetato translúcido champagne. Não pesa na expressão e ilumina os traços do olhar.',
  },
  {
    id: '06',
    name: 'Nezzo Cat-Eye Velvet',
    brand: 'Nezzo Solar',
    price: 429,
    image: '/images/frame-cat-eye.png',
    category: 'Sol',
    frameShape: 'Gatinho',
    size: 'M',
    tags: ['Feminino', 'UV400', 'Editorial'],
    color: 'Preto Ônix',
    companyId: 'nezzo',
    featured: false,
    inStock: true,
    description: 'Design gatinho escultural com cantos elevados. Confere um efeito lifting visual e sofisticação imediata.',
  },
  {
    id: '07',
    name: 'Nezzo Siena Aviator Gold',
    brand: 'Nezzo Solar',
    price: 489,
    image: '/images/frame-aviator.png',
    category: 'Sol',
    frameShape: 'Aviador',
    size: 'G',
    tags: ['Lente Degradê', 'Metal Nobre', 'Proteção UV'],
    color: 'Ouro Polido',
    companyId: 'nezzo',
    featured: false,
    inStock: true,
    description: 'Armação de metal polido dourado com lentes degradê marrom quente. O equilíbrio definitivo entre luxo e proteção solar.',
  },
  {
    id: '08',
    name: 'Nezzo Brisa Oval',
    brand: 'Nezzo Atelier',
    price: 359,
    image: '/images/frame-champagne.png',
    category: 'Grau',
    frameShape: 'Oval',
    size: 'P',
    tags: ['Ergonômico', 'Ultra Confortável', 'Dia a Dia'],
    color: 'Cristal Areia',
    companyId: 'nezzo',
    featured: false,
    inStock: true,
    description: 'Curvas ovais fluidas que suavizam rostos angulosos e quadrados. Ponte anatômica para máximo conforto durante todo o dia.',
  },
  {
    id: '09',
    name: 'Nezzo Titanium Grafite',
    brand: 'Nezzo Atelier',
    price: 499,
    image: '/images/frame-rectangular.png',
    category: 'Grau',
    frameShape: 'Retangular',
    size: 'M',
    tags: ['Alta Resistência', 'Fosco', 'Premium'],
    color: 'Grafite Fosco',
    companyId: 'nezzo',
    featured: false,
    inStock: true,
    description: 'Armação retangular moderna em titânio grafite escovado. Discreta, contemporânea e praticamente indestrutível.',
  },
];
